"""Generated from the XLSForm build. Species columns and ward lookup."""
SPECIES = {'qty_croton': {'category': 'Indigenous',
                'label': 'Croton megalocarpus – Croton / Onera',
                'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_acacia_poly': {'category': 'Indigenous',
                     'label': 'Acacia polyacantha / Senegalia polyacantha – White thorn / Ogongo',
                     'zones': ['LM1']},
 'qty_acacia_xan': {'category': 'Indigenous',
                    'label': 'Acacia xanthoploea / Vachellia xanthophloea – Naivasha thorn',
                    'zones': ['LM1', 'UM2_3']},
 'qty_spathodea': {'category': 'Indigenous',
                   'label': 'Spathodea campanulata – Nandi flame / African tulip',
                   'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_vitex': {'category': 'Indigenous', 'label': 'Vitex kinensis – Meru oak', 'zones': ['UM1']},
 'qty_olea': {'category': 'Indigenous', 'label': 'Olea capensis – Elgon teak', 'zones': ['UM1']},
 'qty_harungana': {'category': 'Indigenous',
                   'label': "Harungana madagacariensis – Dragon's blood tree / Aremo",
                   'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_markhamia': {'category': 'Indigenous',
                   'label': 'Markhamia lutea – Nile tulip',
                   'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_podocarpus': {'category': 'Indigenous', 'label': 'Podocarpus falcatus – Podo', 'zones': ['UM1', 'LM1']},
 'qty_bridelia': {'category': 'Indigenous',
                  'label': 'Bridelia micrantha – Coast goldleaf / Athuno',
                  'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_prunus': {'category': 'Indigenous',
                'label': 'Prunus africana – Red stinkwood / Tenduet',
                'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_khaya': {'category': 'Indigenous', 'label': 'Khaya anthotheca – African mahogany', 'zones': ['UM1']},
 'qty_vepris': {'category': 'Indigenous',
                'label': 'Vepris nobilis – Teclea / Ondati',
                'zones': ['UM1', 'LM1']},
 'qty_maesopsis': {'category': 'Indigenous', 'label': 'Maesopsis eminii – Musizi', 'zones': ['LM1']},
 'qty_albizia_cor': {'category': 'Indigenous',
                     'label': 'Albizia coriaria – Cherry blossom / Mugavu',
                     'zones': ['LM1']},
 'qty_albizia_gum': {'category': 'Indigenous',
                     'label': 'Albizia gummifera – Peacock flower tree',
                     'zones': ['UM1', 'LM1']},
 'qty_cordia': {'category': 'Indigenous', 'label': 'Cordia africana – Sudan teak', 'zones': ['LM1']},
 'qty_avocado': {'category': 'Fruit / agroforestry', 'label': 'Avocado', 'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_loquat': {'category': 'Fruit / agroforestry', 'label': 'Loquat', 'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_syzygium': {'category': 'Fruit / agroforestry',
                  'label': 'Syzygium guineense – Waterberry',
                  'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_white_sapote': {'category': 'Fruit / agroforestry',
                      'label': 'Casimiroa edulis – White sapote',
                      'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_tangerine': {'category': 'Fruit / agroforestry',
                   'label': 'Citrus reticulata – Tangerine',
                   'zones': ['UM1', 'LM1', 'UM2_3']},
 'qty_lemon': {'category': 'Fruit / agroforestry', 'label': 'Citrus lemon – Lemon', 'zones': ['LM1']},
 'qty_orange': {'category': 'Fruit / agroforestry', 'label': 'Citrus sinensis – Orange', 'zones': ['LM1']},
 'qty_tamarind': {'category': 'Fruit / agroforestry',
                  'label': 'Tamarindus indica – Tamarind',
                  'zones': ['LM1']},
 'qty_jackfruit': {'category': 'Fruit / agroforestry',
                   'label': 'Artocarpus heterophyllus – Jackfruit',
                   'zones': ['LM1']}}

WARDS = {'lugaga_wamuluma': {'subcounty': 'Vihiga', 'ward': 'Lugaga-Wamuluma', 'aez_main': 'UM1', 'aez_alt': ''},
 'south_maragoli': {'subcounty': 'Vihiga', 'ward': 'South Maragoli', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'central_maragoli': {'subcounty': 'Vihiga', 'ward': 'Central Maragoli', 'aez_main': 'UM1', 'aez_alt': ''},
 'mungoma': {'subcounty': 'Vihiga', 'ward': 'Mungoma', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'lyaduywa_izava': {'subcounty': 'Sabatia', 'ward': 'Lyaduywa/Izava', 'aez_main': 'UM1', 'aez_alt': ''},
 'west_sabatia': {'subcounty': 'Sabatia', 'ward': 'West Sabatia', 'aez_main': 'UM1', 'aez_alt': ''},
 'chavakali': {'subcounty': 'Sabatia', 'ward': 'Chavakali', 'aez_main': 'UM1', 'aez_alt': ''},
 'north_maragoli': {'subcounty': 'Sabatia', 'ward': 'North Maragoli', 'aez_main': 'UM1', 'aez_alt': ''},
 'wodanga': {'subcounty': 'Sabatia', 'ward': 'Wodanga', 'aez_main': 'UM1', 'aez_alt': ''},
 'busali': {'subcounty': 'Sabatia', 'ward': 'Busali', 'aez_main': 'UM1', 'aez_alt': ''},
 'shiru': {'subcounty': 'Hamisi', 'ward': 'Shiru', 'aez_main': 'UM1', 'aez_alt': 'UM2_3'},
 'gisambai': {'subcounty': 'Hamisi', 'ward': 'Gisambai', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'shamakhokho': {'subcounty': 'Hamisi', 'ward': 'Shamakhokho', 'aez_main': 'UM1', 'aez_alt': ''},
 'banja': {'subcounty': 'Hamisi', 'ward': 'Banja', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'muhudu': {'subcounty': 'Hamisi', 'ward': 'Muhudu', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'tambua': {'subcounty': 'Hamisi', 'ward': 'Tambua', 'aez_main': 'UM1', 'aez_alt': ''},
 'jepkoyai': {'subcounty': 'Hamisi', 'ward': 'Jepkoyai', 'aez_main': 'UM1', 'aez_alt': 'UM2_3'},
 'luanda_township': {'subcounty': 'Luanda', 'ward': 'Luanda Township', 'aez_main': 'UM1', 'aez_alt': ''},
 'wemilabi': {'subcounty': 'Luanda', 'ward': 'Wemilabi', 'aez_main': 'UM1', 'aez_alt': ''},
 'mwibona': {'subcounty': 'Luanda', 'ward': 'Mwibona', 'aez_main': 'UM1', 'aez_alt': ''},
 'luanda_south': {'subcounty': 'Luanda', 'ward': 'Luanda South', 'aez_main': 'UM1', 'aez_alt': 'LM1'},
 'emabungo': {'subcounty': 'Luanda', 'ward': 'Emabungo', 'aez_main': 'UM1', 'aez_alt': ''},
 'north_east_bunyore': {'subcounty': 'Emuhaya',
                        'ward': 'North East Bunyore',
                        'aez_main': 'UM1',
                        'aez_alt': 'LM1'},
 'central_bunyore': {'subcounty': 'Emuhaya', 'ward': 'Central Bunyore', 'aez_main': 'UM1', 'aez_alt': ''},
 'west_bunyore': {'subcounty': 'Emuhaya', 'ward': 'West Bunyore', 'aez_main': 'UM1', 'aez_alt': 'LM1'}}
